### ISSUE TITLE
DOTS Workflow

### ISSUE THREAD

**Issue by communityus** [Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo#2]
Is this the repo we should watch for UI and DOTS working together? I understand it is on the roadmap for UIToolkit.

**Comment by benoit-dupuis** [comment]
Hi, this repository hosts a project we're using to showcase how to use UI Toolkit for making game UI.

Once UI Toolkit is compatible with DOTS, it will most probably be showcased using a different project. We don't have any ETA to share regarding this.

Cheers

**Comment by adammpolak** [comment]
@communityus you can find an example of how to link UI Toolkit and DOTS here: https://app.gitbook.com/@moetsi/s/unity-dots-multiplayer-xr-sample-project/ui-builder-and-ui-toolkit/overview
