### ISSUE TITLE
Project not working with Unity 2020.1.8f1

### ISSUE THREAD

**Issue by styliann-eth** [Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo#3]
Hi,

I cloned the project, updated all the packages with the package manager but the 'TitleScreenManager' does not appear in the Hierarchy and I get some errors.

**Comment by adammpolak** [comment]
@ns2808 

in https://github.com/Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo/blob/master/Packages/manifest.json change line 8 to `    "com.unity.render-pipelines.lightweight": "8.2.0",`

This will cause the materials to update and then it might work. Worked on 2020.15f1.

**Comment by juliaperdigueiroUnity** [comment]
Hello, please report problems on our Forum, we don't regularly watch issues on this repo: https://forum.unity.com/forums/ui-toolkit.178/
Not sure if you're still having issues but in any case the latest version of the package is no longer compatible with Unity 2020.1.
