### ISSUE TITLE
Errors when opening master with Unity 2020.3.1f1

### ISSUE THREAD

**Issue by rYuuk** [Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo#5]
![image](https://user-images.githubusercontent.com/1121080/113417913-bbe2ad00-93c4-11eb-8413-6ed05903d09b.png)

Gets fixed after updating UIBuilder to ` "com.unity.ui.builder": "1.0.0-preview.14"`

**Comment by juliaperdigueiroUnity** [comment]
Please use the Forums to report issues, these issues are not being actively monitored: https://forum.unity.com/forums/ui-toolkit.178/

This issue should be fixed at this point, there was a problem with dependency that wasn't set correctly/in the right order.
