### ISSUE TITLE
com.unity.ui and com.unity.ui.builder not required in unity2021.2-update branch

### ISSUE THREAD

**Issue by edwinbradford** [Unity-Technologies/UIToolkitUnityRoyaleRuntimeDemo#7]
Can I please confirm that the packages `com.unity.ui` and `com.unity.ui.builder` are no longer required in the `unity2021.2-update` branch? They don't exist in the `manifest.json`. All the documentation I've seen up to now specifies they need to be included in the package manager but I'm assuming not if you have 20.21.2 .x or any later version to follow?

**Comment by juliaperdigueiroUnity** [comment]
2021.2 already contains what is known as the `com.unity.ui` package, and 2021.1 already contains what is known as the `com.unity.ui.builder` package. You don't need to install the packages in 2021.2 and it probably will have issues compiling right now even.

In the future please use our Froums, the issues in this repo are not being actively monitored: https://forum.unity.com/forums/ui-toolkit.178/
